apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: neo4j-allow-app-only
spec:
  podSelector:
    matchLabels:
      app: ragleap-neo4j
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: ragleap-app
      ports:
        - protocol: TCP
          port: 7687
        - protocol: TCP
          port: 7474
