package com.ragleap.rag.ingestion;

import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Compares OcrExtractor with the real Python ocr.py on fixture images generated by a Python script
 * (file X, plus X.expected with Python's exact output, or X.error with its message). Set
 * RAGLEAP_OCR_PARITY_DIR to the fixture folder; skipped without it or without the tesseract binary.
 */
@EnabledIfEnvironmentVariable(named = "RAGLEAP_OCR_PARITY_DIR", matches = ".+")
class OcrParityFixturesTest {

    private static String esc(String s) {
        return "'" + s.replace("\\", "\\\\").replace("\n", "\\n").replace("\f", "\\f") + "'";
    }

    @Test
    void matchesRealPythonOutputOnEveryFixture() throws IOException {
        Assumptions.assumeTrue(OcrExtractorTest.tesseractAvailable(), "tesseract is not installed - skipping OCR parity check");
        Path dir = Path.of(System.getenv("RAGLEAP_OCR_PARITY_DIR"));
        List<Path> files;
        try (Stream<Path> s = Files.list(dir)) {
            files = s.sorted().toList();
        }
        List<String> failures = new ArrayList<>();
        int checked = 0;
        for (Path file : files) {
            String name = file.getFileName().toString();
            if (name.endsWith(".expected") || name.endsWith(".error")) {
                continue;
            }
            Path expected = file.resolveSibling(name + ".expected");
            Path error = file.resolveSibling(name + ".error");
            if (!Files.exists(expected) && !Files.exists(error)) {
                continue;
            }
            checked++;
            byte[] raw = Files.readAllBytes(file);
            try {
                String got = OcrExtractor.extractText(raw);
                if (!Files.exists(expected)) {
                    failures.add(name + ": Python raised an error but Java returned " + esc(got));
                } else {
                    String want = Files.readString(expected, StandardCharsets.UTF_8);
                    if (!want.equals(got)) {
                        failures.add(name + ":\n   python = " + esc(want) + "\n   java   = " + esc(got));
                    }
                }
            } catch (IllegalArgumentException e) {
                if (Files.exists(error)) {
                    String want = Files.readString(error, StandardCharsets.UTF_8);
                    boolean ok = want.startsWith("Could not open image data")
                            ? e.getMessage().startsWith("Could not open image data")
                            : want.equals(e.getMessage());
                    if (!ok) {
                        failures.add(name + ": error message differs:\n   python = " + esc(want) + "\n   java   = " + esc(e.getMessage()));
                    }
                } else {
                    failures.add(name + ": Java raised " + esc(String.valueOf(e.getMessage())) + " but Python returned text");
                }
            }
        }
        System.out.println("OCR PARITY: checked=" + checked + " failures=" + failures.size());
        assertTrue(checked > 0, "no fixtures were checked");
        assertTrue(failures.isEmpty(), "Differences from real Python output:\n" + String.join("\n", failures));
    }
}
