{{- if .Values.ingress.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ragleap-app-tls
spec:
  secretName: ragleap-app-tls-secret
  issuerRef:
    name: {{ .Values.ingress.clusterIssuer }}
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.ingress.hostname }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ragleap-app-ingress
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: ragleap-app-tls-secret
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ragleap-app
                port:
                  number: {{ .Values.app.port }}
{{- end }}
